spring:
  application:
    name: jpumpkin-signup
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secretKey: jpumpkin
